api/urls.py
from django.urls import path, include
from . import views

from rest_framework.urlpatterns import format_suffix_patterns
from rest_framework import routers

router = routers.DefaultRouter()
router.register('sheet', views.SheetViewSet)
router.register('category', views.CategoryViewSet)

app_name = 'api'
urlpatterns = [
    path('', include(router.urls)),
    path('api/', include('rest_framework.urls', namespace='rest_framework')),
]

record/urls.py
from django.urls import path
from . import views

# Create your rooting here.
app_name = 'record'
urlpatterns = [
    path('', views.IndexView.as_view(), name="index"),
    path('inquiry/', views.InquiryView.as_view(), name="inquiry"),
    path('record-list/', views.RecordListView.as_view(), name="record_list"),
    path('record-detail/', views.RecordDetailView.as_view(), name="record_detail"),
    path('record-detail/<int:pk>/', views.RecordDetailNextView, name="record_detail_next"),
    path('record-create/', views.RecordCreateView.as_view(), name="record_create"),
    path('record-update/<int:pk>/', views.RecordUpdateView.as_view(), name="record_update"),
    path('record-delete/<int:pk>/', views.RecordDeleteView.as_view(), name="record_delete"),
    path('category-create/', views.CategoryCreateView.as_view(), name="category_create"),
    path('category-update/<int:pk>', views.CategoryUpdateView.as_view(), name="category_update"),
    path('category-delete/<int:pk>', views.CategoryDeleteView.as_view(), name="category_delete"),
    path('sheet-create/', views.SheetCreateView.as_view(), name="sheet_create"),
    path('sheet-update/<int:pk>', views.SheetUpdateView.as_view(), name="sheet_update"),
    path('sheet-delete/<int:pk>/', views.SheetDeleteView.as_view(), name="sheet_delete"),
    path('follow/<slug:username>/', views.FollowView, name="follow"),
    path('unfollow/<slug:username>/', views.UnfollowView, name="unfollow"),
    path('approval/<slug:username>/', views.ApprovalView.as_view(), name="approval"),
]

record/models.py
from django.db import models
from datetime import datetime
from accounts.models import CustomUser

# Create your models here.
class Sheet(models.Model):
    username = models.ForeignKey(CustomUser, verbose_name="ユーザ", on_delete=models.PROTECT)
    name = models.TextField(verbose_name="シート名", blank=True, max_length=30)

    class Meta:
        verbose_name_plural = "Sheet"
    def __str__(self):
        return self.name

class Category(models.Model):
    """ カテゴリーモデル """

    username = models.ForeignKey(CustomUser, verbose_name="ユーザ", on_delete=models.PROTECT)
    sheet = models.ForeignKey('Sheet', verbose_name="シート", on_delete=models.PROTECT)
    name = models.TextField(verbose_name="カテゴリー名", blank=True, max_length=30)
    description = models.TextField(verbose_name="説明", blank=True, null=True, max_length=50)
    axis = models.TextField(verbose_name="軸変数", max_length=10, blank=True, null=True)
    upper = models.FloatField(verbose_name="上限値", blank=True, null=True)
    lower = models.FloatField(verbose_name="下限値", blank=True, null=True)
    class Meta:
        verbose_name_plural ="Category"

    def __str__(self):
        return self.name

class Record(models.Model):
    """ レコードモデル """

    username = models.ForeignKey(CustomUser, verbose_name="ユーザ", on_delete=models.PROTECT)
    category = models.ForeignKey('Category', verbose_name="カテゴリー", on_delete=models.PROTECT)
    value = models.FloatField(verbose_name="数値")
    date = models.DateField(verbose_name="日付", default=datetime.now)

    class Meta:
        verbose_name_plural = 'Record'

record/forms.py
from django import forms
from .models import Record, Category, Sheet
from django.core.mail import EmailMessage

class InquiryForm(forms.Form):
    name = forms.CharField(label='name', max_length=30)
    email = forms.EmailField(label='mail-address')
    title = forms.CharField(label='title', max_length=30)
    message = forms.CharField(label='message', widget=forms.Textarea)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['name'].widget.attrs['class'] = 'form-control col-9'
        self.fields['name'].widget.attrs['placeholder'] = 'お名前を入力してください'

        self.fields['email'].widget.attrs['class'] = 'form-control col-11'
        self.fields['email'].widget.attrs['placeholder'] = 'メールアドレスを入力してください'

        self.fields['title'].widget.attrs['class'] = 'form-control col-11'
        self.fields['title'].widget.attrs['placeholder'] = 'タイトルを入力してください'

        self.fields['message'].widget.attrs['class'] = 'form-control col-12'
        self.fields['message'].widget.attrs['placeholder'] = 'メッセージを入力してください'

        def send_email(self):
            name = self.cleaned_data['name']
            email = self.cleaned_data['email']
            title = self.cleaned_data['title']
            message = self.cleaned_data['message']

            subject = 'お問い合わせ{}'.format(title)
            message = '送信者名: {0}\nメールアドレス: {1}\nメッセージ: {2}'.format(name, email, message)

            from_email = 'admin@example.com'
            to_list = [
                'test@example.com'
            ]
            cc_list = [
                email
            ]

            message = EmailMessage(subject=subject, body=message, from_email=from_email, to=to_list, cc=cc_list)
            message.send()

class RecordCreateForm(forms.ModelForm):
    class Meta:
        model = Record
        fields = ('category', 'date', 'value',)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'

class CategoryCreateForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = ('sheet', 'name', 'description', 'axis', 'upper', 'lower')
        widgets = {
            'name': forms.TextInput(attrs={'class': 'col-sm-8'}),
            'description': forms.TextInput(attrs={'class': 'col-sm-8'}),
            'axis': forms.TextInput(attrs={'class': 'col-sm-8'}),
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'

class SheetCreateForm(forms.ModelForm):
    class Meta:
        model = Sheet
        fields = ('name',)
        widgets = {
            'name': forms.TextInput(attrs={'class': 'col-sm-8'}),
        }


    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'

record/views.py
import logging
from django.http import JsonResponse
from django.urls import reverse_lazy
from django.shortcuts import render, redirect, get_object_or_404
from django.views import generic
from django.db.models import Q
from .forms import InquiryForm, RecordCreateForm, CategoryCreateForm, SheetCreateForm
from .models import Record, Category, Sheet
from accounts.models import CustomUser, Relationship
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin

from rest_framework.views import APIView
from rest_framework.response import Response

from django.contrib.auth import get_user_model
# Create your views here.
logger = logging.getLogger(__name__)


class IndexView(generic.TemplateView):
    template_name = "index.html"

class InquiryView(generic.FormView):
    template_name = "inquiry.html"
    form_class = InquiryForm
    success_url = reverse_lazy('record:inquiry')

    def get_form(self, form_class=None):
        if 'name' in self.request.POST:
            form_data = self.request.POST
        else:
            form_data = self.request.session.get('form_data', None)
        return self.form_class(form_data)

    def from_valid(self, form):
        form.send_email()
        messages.success(self.request, 'メッセージを送信しました')
        logger.info('Inquiry sent by {}'.format(form.cleaned_data['name']))
        return super(InquiryView, self).form_valid(form)

class RecordListView(LoginRequiredMixin, generic.ListView):
    model = Record, CustomUser, Relationship
    template_name = 'record_list.html'

    def get(self, request, *args, **kwargs):
        queryset = Record.objects.filter(username=self.request.user).order_by('category')
        record = queryset.order_by('date')
        date = Record.objects.filter(username=self.request.user).values_list('date', flat=True).order_by('date').distinct()
        cate_list = Category.objects.filter(username=self.request.user)
        sheet_list = Sheet.objects.filter(username=self.request.user)
        relation_list = Relationship.objects.filter(user=self.request.user, is_approval=True)
        follow = Relationship.objects.filter(user=self.request.user).values_list('follow', flat=True )
        follower = Relationship.objects.filter(follow=self.request.user, is_approval=False)

        if follow:
            for follow in follow:
                follow_record = Record.objects.filter(username=follow).order_by('date')
                follow_cate = Category.objects.filter(username=follow)
                follow_date = Record.objects.filter(username=follow).values_list('date', flat=True).order_by('date').distinct()
        else:
            follow_record = ""
            follow_cate = ""
            follow_date = ""

        q_word = self.request.GET.get('query')

        if q_word:
            object_list = CustomUser.objects.filter(Q(username__icontains=q_word))
        else:
            object_list = CustomUser.objects.all()
        
        context = {
            'queryset': queryset,
            'record': record,
            'date': date,
            'cate_list': cate_list,
            'sheet_list': sheet_list,
            'relation_list': relation_list,
            'follow': follow,
            'follow_record': follow_record,
            'follow_cate': follow_cate,
            'follow_date': follow_date,
            'follower': follower,
            'object_list': object_list,

        }
        return render(request, 'record_list.html', context)

class RecordDetailView(LoginRequiredMixin, generic.ListView):
    model = Category
    template_name = 'record_detail.html'

    def get(self, request, *args, **kwargs):
        category_list = Category.objects.filter(username=self.request.user)
        sheet_list = Sheet.objects.filter(username=request.user)
        context = {
            'category_list': category_list,
            'sheet_list': sheet_list,
        }
        return render(request, 'record_detail.html', context)

def RecordDetailNextView(request, pk):
    record_list = Record.objects.filter(username=request.user, category=pk).order_by('-date')
    context = {
        'record_list': record_list
        }
    return render(request, 'record_detail_next.html', context)

class RecordCreateView(LoginRequiredMixin, generic.CreateView):
    model = Record
    template_name = 'record_create.html'
    form_class = RecordCreateForm
    success_url = reverse_lazy('record:record_list')

    def form_valid(self, form):
        record = form.save(commit=False)
        record.username = self.request.user
        record.save()
        messages.success(self.request, '記録を作成しました')
        return super().form_valid(form)

    def form_invalid(self, form):
        messages.error(self.request, "記録の作成に失敗しました")
        return super().form_invalid(form)

class RecordUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Record
    template_name = 'record_update.html'
    form_class = RecordCreateForm

    def get_success_url(self):
        return reverse_lazy('record:record_list')

    def form_valid(self, form):
        messages.success(self.request, '記録を更新しました')
        return super().form_valid(form)

    def form_invalid(self, form):
        messages.success(self.request, '記録の更新に失敗しました')
        return super().form_invalid(form)

class RecordDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Record
    template_name = 'record_delete.html'
    success_url = reverse_lazy('record:record_list')

    def delete(self, request, *args, **kwargs):
        messages.success(self.request, '記録を削除しました')
        return super().delete(request, *args, **kwargs)

class CategoryCreateView(LoginRequiredMixin, generic.CreateView):
    model = Category
    template_name = 'category_create.html'
    form_class = CategoryCreateForm
    success_url = reverse_lazy('record:record_list')

    def form_valid(self, form):
        category = form.save(commit=False)
        category.username = self.request.user
        category.save()
        messages.success(self.request, 'カテゴリを作成しました')
        return super().form_valid(form)

    def form_invalid(self, form):
        messages.error(self.request, 'カテゴリの作成に失敗しました')
        return super().form_invalid(form)

class CategoryUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Category
    template_name = 'category_update.html'
    form_class = CategoryCreateForm

    def get_success_url(self):
        return reverse_lazy('record:record_list')

    def form_valid(self, form):
        messages.success(self.request, 'カテゴリーを更新しました')
        return super().form_valid(form)

    def form_invalid(self, form):
        messages.success(self.request, 'カテゴリーの更新に失敗しました')
        return super().form_invalid(form)

class CategoryDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Category
    template_name = 'category_delete.html'
    success_url = reverse_lazy('record:record_list')

    def delete(self, request, *args, **kwargs):
        messages.success(self.request, 'カテゴリーを削除しました')
        return super().delete(request, *args, **kwargs)

class SheetCreateView(LoginRequiredMixin, generic.CreateView):
    model = Sheet
    template_name = 'sheet_create.html'
    form_class = SheetCreateForm
    success_url = reverse_lazy('record:record_list')

    def form_valid(self, form):
        sheet = form.save(commit=False)
        sheet.username = self.request.user
        sheet.save()
        messages.success(self.request, 'シートを作成しました')
        return super().form_valid(form)

    def form_invalid(self, form):
        messages.error(self.request, 'シートの作成に失敗しました')
        return super().form_invalid(form)

class SheetUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Sheet
    template_name = 'sheet_update.html'
    form_class = SheetCreateForm

    def get_success_url(self):
        return reverse_lazy('record:record_list')

    def form_valid(self, form):
        messages.success(self.request, 'シートを更新しました')
        return super().form_valid(form)

    def form_invalid(self, form):
        messages.success(self.request, 'シートの更新に失敗しました')
        return super().form_invalid(form)

class SheetDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Sheet
    template_name = 'sheet_delete.html'
    success_url = reverse_lazy('record:record_list')

    def delete(self, request, *args, **kwargs):
        messages.success(self.request, 'シートを削除しました')
        return super().delete(request, *args, **kwargs)

class Share(LoginRequiredMixin, generic.ListView):
    model = CustomUser
    template_name = 'share.html'

    slug_field = 'username'
    slug_url_kwarg = 'username'

    def get_queryset(self):
        q_word = self.request.GET.get('query')

        if q_word:
            object_list = CustomUser.objects.filter(Q(username__icontains=q_word))
        else:
            object_list = CustomUser.objects.all()
        return object_list

    def get_context_data(self, **kwargs):
        context = super(Share, self).get_context_data(**kwargs)
        username = self.kwargs['username']
        context['username'] = username
        context['follow'] = Relationship.objects.filter(user__username=username).count()
        context['user'] = Relationship.objects.filter(follow__username=username).count()

        if username is not self.request.user:
            result = Relationship.objects.filter(user__username=self.request.user).filter(follow__username=username)
            context['relation'] = True if result else False
        return context

def FollowView(request, *args, **kwargs):
    try:
        user = CustomUser.objects.get(username=request.user.username)
        follow = CustomUser.objects.get(username=kwargs['username'])
    except CustomUser.DoesNotExist:
        messages.warning(request, '{}は存在しません'.format(kwargs['username']))
        return redirect('record:index')
    if user == follow:
        messages.warning(request, 'フォローできません')
    else:

record/templates/record_create.html
{% extends 'base.html' %}
{% load static %}
{% block title %}記録作成 | Blood Records{% endblock %}
{% block active_record_list %}active{% endblock %}

{% block contents %}
<div class="container">
    <div class="row">
        <div class="my-div-style">
            <form action="" method="post">
            {% csrf_token %}
                    {{form.as_table}}
                <div class="mt-2">
                    <button class="btn btn-primary">作成</button>
                </div>
            </form>
            <a href="{% url 'record:category_create' %}">Category新規作成>></a><br>
            <a href="{% url 'record:sheet_create' %}">Sheet新規作成>></a>
        </div>
    </div>
</div>
{% endblock %}

record/templates/record_detail.html
{% extends 'base.html' %}
{% load static %}
{% block title %}記録詳細 | Blood Records{% endblock %}
{% block active_record_detail %}active{% endblock %}

{% block contents %}
<div class="container">
    <div class="row">
        <div class="my-div-style">
            <p>Sheet</p>
            <table class="table">
            {% for sheet in sheet_list %}
                <tr>
                    <td>{{ sheet.name }}</td>
                    <td><a href="{% url 'record:sheet_update' sheet.pk %}">編集</a></td>
                    <td><a href="{% url 'record:sheet_delete' sheet.pk %}">削除</a></td>
                </tr>
            {% endfor %}
            </table>
            <p>Category</p>
            <table class="table">
            {% for category in category_list %}
                <tr>
                    <td><a href="{% url 'record:record_detail_next' category.pk %}">{{ category.name }}</a></td>
                    <td>{{ category.description }}</td>
                    <td><a href="{% url 'record:category_update' category.pk %}">編集</a></td>
                    <td><a href="{% url 'record:category_delete' category.pk %}">削除</a></td>
                </tr>
            {% endfor %}
            </table>
        </div>
    </div>
</div>
{% endblock %}

record/templates/record_detail_next.html
{% extends 'base.html' %}
{% load static %}
{% block title %}記録詳細 | Blood Records{% endblock %}
{% block active_record_detail %}active{% endblock %}

{% block contents %}
<div class="container">
    <div class="row">
        <div class="my-div-style">
            <p>{{ record.category.name }}</p>
            <table class="table">
            <tr>
                <td>Date</td>
                <td>Value</td>
            </tr>
            {% for record in record_list %}
            <tr>
                <td>{{ record.date }}</td>
                <td>{{ record.value }}</td>
                <td><a href="{% url 'record:record_update' record.pk %}">編集</a></td>
                <td><a href="{% url 'record:record_delete' record.pk %}">削除</a></td>
            </tr>
            {% endfor %}
            </table>
        </div>
    </div>
</div>
{% endblock %}

record/templates/record_list.html
{% extends 'base.html' %}
{% load static %}
{% block title %}記録一覧 | Blood Records{% endblock %}
{% block active_record_list %}active{% endblock %}
{% block user %}active{% endblock %}
{% block username %}Hellow {{ user }} !{% endblock %}

{% block head %}
{% endblock %}

{% block extrajs %}
    <script src="https://cdn.jsdelivr.net/npm/chart.js@2.9.3/dist/Chart.min.js"></script>
    <script src ="https://cdnjs.cloudflare.com/ajax/libs/chartjs-plugin-annotation/0.5.7/chartjs-plugin-annotation.min.js"></script>
{% endblock %}


{% block contents %}
<div class="container">
    <div class="row">
        <div class="my-div-style">
            <div class="float-right ml-lg-5 pl-lg-5">
                <form action="" method="get">
                {% csrf_token %}
                    <div class="row">
                        <input class="form-control col-8" type="text" name="query" value="{{ request.GET.query }}">
                        <input class="btn btn-primary" type="submit" value="検索">
                    </div>
                </form>
                {% for follower in follower %}
                    <a class="btn-block p-1 bg-light rounded" href="{% url 'record:approval' follower.user %}">{{ follower.user }}からのフォローを承認する<a><br>
                {% endfor %}
                {% for user in object_list %}
                    <div class="row mt-3">
                        {{ user.username }}
                        {% if user.id == follow %}
                            <a class="ml-3 p-1 bg-light rounded" href="{% url 'record:unfollow' user.username %}">フォロー解除<a>
                        {% else %}
                            <a class="ml-3 p-1 bg-light rounded" href="{% url 'record:follow' user.username %}">フォローする<a>
                        {% endif %}
                    </div>
                {% endfor %}
            </div>
            {% for sheet in sheet_list %}
                <div class="float-left mt-lg-3 p-3">
                        <h3 class="h3">{{ sheet.name }}</h3>
                        <canvas id="line-graph{{ forloop.counter }}" width="700" height="300"></canvas>
                </div>
            {% endfor %}
            {% for relation in relation_list %}
                <div class="float-left mt-lg-3 p-3">
                    <h3 class="h3">{{ relation.follow }}</h3>
                    <canvas id="line-graph-follow{{ forloop.counter }}" width="700" height="300"></canvas>
                </div>
            {% endfor %}
                <script>
                    window.onload = function() {
                    {% for sheet in sheet_list %}
                        var ctx{{ forloop.counter }} = document.getElementById('line-graph{{ forloop.counter }}').getContext('2d');
                        var myChart{{ forloop.counter }} = new Chart(ctx{{ forloop.counter }}, config{{ forloop.counter }});
                    {% endfor %}
                    {% if relation_list %}
                        {% for relation in relation_list %}
                            var ctx_follow{{ forloop.counter }} = document.getElementById('line-graph-follow{{ forloop.counter }}').getContext('2d');
                            var myChart_follow{{ forloop.counter }} = new Chart(ctx_follow{{ forloop.counter }}, config_follow{{ forloop.counter }});
                        {% endfor %}
                    {% endif %}
                    };
                    var annotationColor = 'rgba(0, 255, 128, 0.2)';
                    
                    function removeBackgroundColor(chart, legendItem){
                        {% for cate in cate_list %}
                            if(legendItem.datasetIndex == {{ forloop.counter|add:"-1" }}){
                                if(chart.annotation.elements['{{ forloop.counter|add:"-1" }}'] != null)
                                    chart.annotation.elements['{{ forloop.counter|add:"-1" }}'].options.backgroundColor = 'rgba(0, 0, 0, 0)';
                            }
                        {% endfor %}
                    }

                    function putBackgroundColor(chart, legendItem){
                        {% for cate in cate_list %}
                        if(legendItem.datasetIndex == {{ forloop.counter|add:"-1" }}){
                            if(chart.annotation.elements['{{ forloop.counter|add:"-1" }}'] != null)
                                chart.annotation.elements['{{ forloop.counter|add:"-1" }}'].options.backgroundColor = annotationColor;
                        }
                        {% endfor %}
                    }

                    function onClick (e, legendItem) {
                        var index = legendItem.datasetIndex;
                        var ci = this.chart;
                        var meta = ci.getDatasetMeta(index);

                        meta.hidden = meta.hidden === null ? !ci.data.datasets[index].hidden : null;

                        if(meta.hidden != null)
                            removeBackgroundColor(ci, legendItem);
                        else
                            putBackgroundColor(ci, legendItem);
                        
                        ci.update();
                    }
                    {% for sheet in sheet_list %}
                        var config{{ forloop.counter }} = {
                            type: 'line',
                            data: {
                                labels: [
                                    {% for today in date %}
                                        '{{ today }}',
                                    {% endfor %}
                                ],
                                datasets: [
                                {% for cate in cate_list %}
                                {% if cate.sheet.id == sheet.id %}
                                {
                                    label: '{{ cate.name }}',
                                    data: [
                                            {% for record in record %}
                                            {% if record.category.name == cate.name %}
                                                        {{ record.value }},
                                            {% endif %}
                                            {% endfor %}
                                    ],
                                    {% if forloop.first %}
                                        borderColor: 'rgba(0, 128, 128, 0.5)',
                                    {% elif forloop.counter == 2  %}
                                        borderColor: 'rgba(128, 0, 128, 0.5)',
                                    {% elif forloop.counter == 3  %}
                                        borderColor: 'rgba(0, 128, 0, 0.5)',
                                    {% elif forloop.counter == 4  %}
                                        borderColor: 'rgba(0, 0, 128, 0.5)',
                                    {% else %}
                                        borderColor: 'rgba(128, 128, 0, 0.5)',
                                    {% endif %}
                                    fill: false
                                },
                                {% endif %}
                                {% endfor %}
                                ],
                            },
                            options: {
                                legend: {
                                    onClick: onClick,
                                },
                                annotation: {
                                    annotations: [
                                    {% for cate in cate_list %}
                                    {% if cate.sheet.id == sheet.id %}
                                    {
                                        id: "{{ forloop.counter|add:'-1' }}",
                                        drawTime: 'afterDatasetsDraw', // overrides annotation.drawTime if set
                                        type: 'box',
                                        mode: 'horizontal',
                                        yScaleID: 'y-axis-0',
                                        yMax: {{ cate.upper }},
                                        yMin: {{ cate.lower }},
                                        backgroundColor: annotationColor,
                                        borderColor: annotationColor,
                                        borderWidth: 1,
                                    },
                                    {% endif %}
                                    {% endfor %}
                                    ]
                                }
                            }
                        };
                    {% endfor %}

                    {% if relation_list %}
                    {% for relation in relation_list %}
                        var config_follow{{ forloop.counter }} = {
                            type: 'line',
                            data: {
                                labels: [
                                    {% for f_today in follow_date %}
                                        '{{ f_today }}',
                                    {% endfor %}
                                ],
                                datasets: [
                                {% for f_cate in follow_cate %}
                                {
                                    label: '{{ f_cate.name }}',
                                    data: [
                                        {% for f_record in follow_record %}
                                            {% if f_record.category.name == f_cate.name %}
                                                {{ f_record.value }},
                                            {% endif %}
                                        {% endfor %}
                                    ],
                                    {% if forloop.first %}
                                        borderColor: 'rgba(0, 128, 128, 0.5)',
                                    {% elif forloop.counter == 2  %}
                                        borderColor: 'rgba(128, 0, 128, 0.5)',
                                    {% elif forloop.counter == 3  %}
                                        borderColor: 'rgba(0, 128, 0, 0.5)',
                                    {% elif forloop.counter == 4  %}
                                        borderColor: 'rgba(0, 0, 128, 0.5)',
                                    {% else %}
                                        borderColor: 'rgba(128, 128, 0, 0.5)',
                                    {% endif %}
                                    fill: false
                                },
                                {% endfor %}
                                ],
                            },
                            options: {
                                legend: {
                                    onClick: onClick,
                                },
                                annotation: {
                                    annotations: [
                                    {% for f_cate in follow_cate %}
                                    {
                                        id: "{{ forloop.counter|add:'-1' }}",
                                        drawTime: 'afterDatasetsDraw', // overrides annotation.drawTime if set
                                        type: 'box',
                                        mode: 'horizontal',
                                        yScaleID: 'y-axis-0',
                                        yMax: {{ f_cate.upper }},
                                        yMin: {{ f_cate.lower }},
                                        backgroundColor: annotationColor,
                                        borderColor: annotationColor,
                                        borderWidth: 1,
                                    },
                                    {% endfor %}
                                    ]
                                }
                            }
                        };
                    {% endfor %}
                    {% endif %}
                </script>
        </div>
    </div>
</div>
{% endblock %}